version: '3.8'

services:
  password-checker:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      # Optional: Mount rockyou.txt if you have it locally
      # - ./rockyou.txt:/app/rockyou.txt:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
